version: '2.3'

services:
  db:
    image: postgres:11.8-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rss_reader_dev
    ports:
      - 5432:5432
